---
# Deploy the LAMP stack, laravel, and the application.

- name: common node configuration
  hosts: all
  sudo: true
  roles:
    - common

- name: install, configure, and deploy the database tier
  hosts: dbserver
  sudo: true
  roles:
    - db

- name: install and configure the web tier
  hosts: webservers
  sudo: true
  roles:
    - web

