---
# ------------------------------------------------------------------------- #
# Installs and configures the web server, and deploys the web application.  #
# ------------------------------------------------------------------------- #

# Update Cache

- name: update apt cache
  apt: update_cache=yes cache_valid_time=7200

# Apache

- name: install apache
  apt: name=apache2 state=latest

- name: enable and start apache service
  service: name=apache2 state=started enabled=yes

- name: remove the default apache site
  file: path=/etc/apache2/sites-enabled/{{ item }} state=absent
  with_items:
    - 000-default.conf
    - default-ssl.conf

# PHP

- name: install php and dependencies
  apt: name={{ item }} state=latest
  with_items:
    - mysql-client
    - php5
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-xdebug

- name: configure php5 mcrypt
  file: src=/etc/php5/mods-available/mcrypt.ini dest=/etc/php5/conf.d/mcrypt.ini owner=root group=root state=link

- name: php5enmod mcrypt
  command: php5enmod mcrypt

- name: enable mod_rewrite
  command: a2enmod rewrite

- name: restart apache2
  service: name=apache2 state=restarted

# Composer

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: configure composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: update composer
  command: composer self-update

# Memcached

- name: install memcached
  apt: name=memcached state=present

# Checkout Site

- name: checkout site repository from git
  git: repo={{ repository }} dest={{ site_dir }} accept_hostkey=yes

# Configure Site

- name: clear the environment
  file: path={{ site_dir }}/.environment.php state=absent

- name: configure site environment
  template: src={{ site_dir }}/.environment.php.j2 dest=/tmp/.environment.php

- name: copy site environment file # VirtualBox workaround
  command: cp /tmp/.environment.php {{ site_dir }}/.environment.php

- name: install composer components
  command: composer update chdir={{ site_dir }}

- name: install application
  command: php artisan app:install --force chdir={{ site_dir }}

# Configure Apache

- name: configure site in apache
  command: echo 'hello site!'

